# Generated by Django 2.1 on 2019-11-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField()),
                ('publisher', models.TextField(max_length=40)),
                ('typec', models.TextField()),
                ('about', models.TextField()),
                ('available', models.BooleanField(default=True)),
                ('issuing_date', models.DateField(blank=True, null=True)),
                ('returning_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
